# Generated by Django 2.2.1 on 2022-05-22 18:21

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('cod_articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articulos.Articulo')),
                ('cod_pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.Pedido')),
            ],
            options={
                'verbose_name': 'ArticuloPedido',
                'verbose_name_plural': 'ArticulosPedidos',
                'ordering': ['-created'],
            },
        ),
    ]
