# Generated by Django 2.2.1 on 2022-05-23 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_auto_20220523_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gastos.Proveedor'),
        ),
    ]
