# Generated by Django 2.2.1 on 2022-05-22 13:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoGasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Grupo de gasto',
                'verbose_name_plural': 'Grupos de Gastos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_documento', models.IntegerField(blank=True, choices=[(1, 'Nif'), (2, 'Nie'), (3, 'Cif')], db_index=True, default=3, null=True)),
                ('num_documento', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_alta', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('dir_calle', models.CharField(blank=True, max_length=255, null=True, verbose_name='calle')),
                ('dir_numero', models.CharField(blank=True, max_length=25, null=True, verbose_name='numero')),
                ('dir_piso_puerta', models.CharField(blank=True, max_length=255, null=True, verbose_name='piso puerta')),
                ('cod_postal', models.IntegerField(blank=True, null=True)),
                ('poblacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.Poblacion', verbose_name='Población')),
                ('provincias', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.Provincias', verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('Descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('num_factura', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_doc', models.IntegerField(blank=True, choices=[(1, 'Factura'), (2, 'Ticket')], db_index=True, default=2, null=True)),
                ('iva', models.IntegerField(blank=True, choices=[(1, 'Iva General (21%)'), (2, 'Iva Reducido (10%)'), (3, 'Iva Superreducido (4%)')], db_index=True, default=1, null=True)),
                ('forma_pago', models.IntegerField(blank=True, choices=[(1, 'Tarjeta de Credito'), (2, 'Transferencia Bancaria'), (3, 'Efectivo'), (4, 'Ingreso Bancario')], db_index=True, default=3, null=True)),
                ('almacenable', models.BooleanField(default=False)),
                ('unidades', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_caducidad', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='documentos_gastos')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastos.Proveedor')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-created'],
            },
        ),
    ]
