# Generated by Django 2.2.1 on 2022-05-22 14:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('code', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'tipo documento',
                'verbose_name_plural': 'tipo documentos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('tipo_documento', models.IntegerField(blank=True, choices=[(1, 'Nif'), (2, 'Nie'), (3, 'Pasaporte')], db_index=True, default=1, null=True)),
                ('num_documento', models.CharField(blank=True, max_length=9, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('sexo', models.IntegerField(blank=True, choices=[(1, 'Hombre'), (2, 'Mujer')], db_index=True, default=1, null=True)),
                ('estado_civil', models.IntegerField(blank=True, choices=[(1, 'Casado'), (2, 'Soltero'), (3, 'Viudo'), (4, 'Divorciado')], default=2, null=True)),
                ('hijos', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('perfil', models.IntegerField(blank=True, choices=[(1, 'Administración'), (2, 'Almacen'), (3, 'Mantenimiento'), (4, 'Transporte'), (5, 'Direccion'), (6, 'Contable')], db_index=True, default=2, null=True)),
                ('dir_calle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Calle')),
                ('dir_num', models.CharField(blank=True, max_length=255, null=True, verbose_name='Número')),
                ('dir_piso', models.CharField(blank=True, max_length=255, null=True, verbose_name='Piso/Planta')),
                ('codigo_postal', models.CharField(blank=True, max_length=15, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('movil', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tipo_contrato', models.IntegerField(blank=True, choices=[(1, 'Temporal 3 Meses'), (2, 'Temporal 6 Meses'), (3, 'Temporal 9 Meses'), (4, 'Temporal 12 Meses'), (5, 'Indefinido'), (6, 'En prácticas')], db_index=True, default=1, null=True, verbose_name='Tipo de Contrato')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('fecha_alta', models.DateField(blank=True, null=True, verbose_name='Fecha de Alta')),
                ('iban', models.CharField(blank=True, max_length=24, null=True, verbose_name='IBAN')),
                ('poblacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.Poblacion', verbose_name='Población')),
                ('provincias', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.Provincias', verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'Profesional',
                'verbose_name_plural': 'Profesionales',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('etiqueta', models.CharField(max_length=255)),
                ('fecha_documento', models.DateField(default=django.utils.timezone.now)),
                ('documento', models.FileField(blank=True, null=True, upload_to='documentos')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profesionales.Profesional')),
                ('tipodocumento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profesionales.TipoDocumentos')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Bajas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('etiqueta', models.CharField(max_length=255)),
                ('fecha_documento', models.DateField(default=django.utils.timezone.now)),
                ('bajas', models.FileField(blank=True, null=True, upload_to='bajas_profesionales')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profesionales.Profesional')),
            ],
            options={
                'verbose_name': 'baja',
                'verbose_name_plural': 'bajas',
                'ordering': ['-created'],
            },
        ),
    ]
